import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dns from "node:dns"
dns.setServers(["8.8.8.8","8.8.4.4"])


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vibe Code Ceramics",
  description: "Generated by Tasdid",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        {children}
        
        </body>
    </html>
  );
}
